
#-----------------------------twitterAPI--------------------------------------------
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  #AWSAccessKeyId: <%= ENV["AWS_ACCESS_KEYID"] %>
  #AWSSecretKey: <%= ENV["AWS_SECRET_KEY"] %>
  #associate_tag: <%= ENV["ASSOCIATE_TAG_ID"]>
