
default_twitter: &default_twitter
  twitter_api_key: CVTq874NApWzjNiXRdFLHm4VL #'先ほど取得したAPI key
  twitter_api_secret: 7Skcen1PAkbdLucRFmUcK8x26YAWh09q5fooGqsCVyaRgzDSqn #'先ほど取得したAPI secret'

#デフォルトのＡＰＩキーと本番環境のＡＰＩキーは別物を用意することでセキュリティを担保すること
#記述する順序は頭から読み出すので注意する

development:
  secret_key_base: 36215b978872c93ddf1a4c1dde5e6c2955cae9688d8d8f3d003af6d7cadb9d123d1ff25176f5484db895ed1b57d9d21e23cdfb89833e3c6d29dccfef622e3d4c
  <<: *default_twitter

test:
  secret_key_base: d59596ace3f3717bceb1b159dca93f3f16d5c9a1c6aae339f80940f51ac00d23ad1de17e371be59b80165497a74bdbb5ab8657651a55f40b448ad4e95d8e82c3
  <<: *default_twitter
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
#-----------------------------twitterAPI--------------------------------------------
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  #AWSAccessKeyId: <%= ENV["AWS_ACCESS_KEYID"] %>
  #AWSSecretKey: <%= ENV["AWS_SECRET_KEY"] %>
  #associate_tag: <%= ENV["ASSOCIATE_TAG_ID"]>
